//! GitScale's man pages: written beside the binary, where `man` finds them
//! without any setup, so `git scale --help` — which git turns into `man
//! git-scale` — shows them.

use crate::support::TestEnv;
use std::path::PathBuf;
use std::process::Command;

/// Where the binary under test writes its pages.
fn man1() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_gitscale"))
        .canonicalize()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("share/man/man1")
}

fn stamp() -> String {
    format!(
        ".\\\" generated by gitscale {}\n",
        env!("CARGO_PKG_VERSION")
    )
}

/// `hook install` writes every page, stamped with this version; a page
/// another version wrote is rewritten by the next interactive run; and
/// `man`'s own search path, from `PATH` alone, holds them.
#[test]
fn normal_001_hook_install_writes_the_pages_where_man_finds_them() {
    let env = TestEnv::new("man_pages");
    let home = env.repos_remote.join("home");
    std::fs::create_dir_all(&home).unwrap();
    crate::support::run_git_pub(
        &env.playground,
        &["commit", "-q", "--allow-empty", "-m", "x"],
    );
    let out = Command::new(env!("CARGO_BIN_EXE_gitscale"))
        .args([
            "hook",
            "install",
            "--local",
            "-C",
            env.playground.to_str().unwrap(),
        ])
        .env("HOME", &home)
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        String::from_utf8_lossy(&out.stdout).contains("man pages in"),
        "{}",
        String::from_utf8_lossy(&out.stdout)
    );
    for page in [
        "gitscale",
        "git-scale",
        "git-topic",
        "git-upgrade",
        "git-explain",
    ] {
        let text = std::fs::read_to_string(man1().join(format!("{}.1", page))).unwrap();
        assert!(text.starts_with(&stamp()), "{}", page);
    }

    // Written by another version: an interactive run brings it up to date.
    std::fs::write(
        man1().join("git-scale.1"),
        ".\\\" generated by gitscale 0.0.1\n",
    )
    .unwrap();
    env.write_config("[repos]\n");
    let ran = Command::new("script")
        .args([
            "-qec",
            &format!("'{}' --color never ls", env!("CARGO_BIN_EXE_gitscale")),
            "/dev/null",
        ])
        .current_dir(&env.playground)
        .env("HOME", &home)
        .output();
    if ran.is_ok_and(|o| o.status.success()) {
        let text = std::fs::read_to_string(man1().join("git-scale.1")).unwrap();
        assert!(text.starts_with(&stamp()), "{}", text);
    }

    // `man` looks in `<bin>/../share/man` for every `bin` on PATH.
    let bin = man1()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("debug");
    let path = format!(
        "{}:{}",
        bin.display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let Ok(listed) = Command::new("manpath")
        .env_remove("MANPATH")
        .env("PATH", &path)
        .output()
    else {
        return;
    };
    let listed = String::from_utf8_lossy(&listed.stdout).into_owned();
    let share = man1().parent().unwrap().to_path_buf();
    assert!(
        listed
            .split(':')
            .any(|p| std::path::Path::new(p.trim()) == share),
        "{} not in {}",
        share.display(),
        listed
    );
    let found = Command::new("man")
        .args(["-w", "git-scale"])
        .env_remove("MANPATH")
        .env("PATH", &path)
        .output();
    if let Some(found) = found.ok().filter(|o| o.status.success()) {
        let found = String::from_utf8_lossy(&found.stdout);
        if found.contains("git-scale") {
            assert_eq!(found.trim(), man1().join("git-scale.1").to_str().unwrap());
        }
    }
}
