[repos]
"gsdemo-sso" = { url = "https://github.com/avkonst/gsdemo-sso.git", revision = "master" }
"gsdemo-sso-sdk" = { url = "https://github.com/avkonst/gsdemo-sso-sdk.git", revision = "master", mode = "readonly" }
"gsdemo-core" = { url = "https://github.com/avkonst/gsdemo-core.git", revision = "master" }
"gsdemo-core-sdk" = { url = "https://github.com/avkonst/gsdemo-core-sdk.git", revision = "master", mode = "readonly" }
"gsdemo-frontend" = { url = "https://github.com/avkonst/gsdemo-frontend.git", revision = "master" }
"gsdemo-sharedlibs" = { url = "https://github.com/avkonst/gsdemo-sharedlibs.git", revision = "master", mode = "readonly" }
"gsdemo-compose" = { url = "https://github.com/avkonst/gsdemo-compose.git", revision = "master" }
"gsdemo-argocd" = { url = "https://github.com/avkonst/gsdemo-argocd.git", revision = "master" }
