[storage]
url = "file:///tmp/gitscale-demo-bucket"

[repos]
"gsdemo-sso" = { url = "https://github.com/avkonst/gsdemo-sso.git", revision = "main" }
"gsdemo-core" = { url = "https://github.com/avkonst/gsdemo-core.git", revision = "master" }
"gsdemo-frontend" = { url = "https://github.com/avkonst/gsdemo-frontend.git", revision = "master" }
"gsdemo-sharedlibs" = { url = "https://github.com/avkonst/gsdemo-sharedlibs.git", revision = "master" }
"gsdemo-compose" = { url = "https://github.com/avkonst/gsdemo-compose.git", revision = "master" }
"gsdemo-argocd" = { url = "https://github.com/avkonst/gsdemo-argocd.git", revision = "master" }

[hooks]
post_sync = "echo 'post-sync hook executed successfully'"
