//! GitScale's man pages, written from the command line clap knows.
//!
//! `git scale --help` is not GitScale's to answer: git turns it into `man
//! git-scale` before GitScale runs. So the pages are written where `man`
//! looks without any setup — `<binary dir>/../share/man/man1`, which it
//! searches for every `bin` directory on `PATH` — by `hook install`, and
//! rewritten by any interactive run once the version changed, as the agent
//! skill is kept current. A directory this user does not own, or cannot
//! write, belongs to a system or package install, which ships its own pages:
//! it is left alone, quietly.

use std::path::{Path, PathBuf};

const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The first line of every page, which says which version wrote it.
fn stamp() -> String {
    format!(".\\\" generated by gitscale {}\n", VERSION)
}

/// Each page's file name and the command it documents.
fn pages() -> Vec<(&'static str, clap::Command)> {
    let full = crate::command();
    let sub = |name: &str, page: &'static str| {
        full.find_subcommand(name)
            .cloned()
            .expect("a gitscale subcommand")
            .name(page)
            .bin_name(page.replacen('-', " ", 1))
            .version(VERSION)
    };
    vec![
        (
            "gitscale",
            full.clone().name("gitscale").bin_name("gitscale"),
        ),
        (
            "git-scale",
            full.clone().name("git-scale").bin_name("git scale"),
        ),
        ("git-topic", sub("topic", "git-topic")),
        ("git-upgrade", sub("upgrade", "git-upgrade")),
        ("git-explain", sub("explain", "git-explain")),
    ]
}

/// The page for `command`, as roff.
pub fn render(command: clap::Command) -> Vec<u8> {
    let mut text = stamp().into_bytes();
    let _ = clap_mangen::Man::new(command).render(&mut text);
    text
}

/// Where the pages of the running binary go.
pub fn dir() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?.canonicalize().ok()?;
    Some(exe.parent()?.parent()?.join("share/man/man1"))
}

/// Write every page into `dir`, when it is this user's to write to.
/// `None` when it is not, or when writing failed.
pub fn write_to(dir: &Path) -> Option<PathBuf> {
    if !ours(dir) {
        return None;
    }
    std::fs::create_dir_all(dir).ok()?;
    for (name, command) in pages() {
        let path = dir.join(format!("{}.1", name));
        let partial = dir.join(format!(".{}.1.partial", name));
        std::fs::write(&partial, render(command)).ok()?;
        std::fs::rename(&partial, &path).ok()?;
    }
    Some(dir.to_path_buf())
}

/// `hook install`: write the pages beside the binary.
pub fn write() -> Option<PathBuf> {
    write_to(&dir()?)
}

/// An interactive run: rewrite the pages when ones written by another
/// version are there. Never creates them.
pub fn refresh() {
    let Some(dir) = dir() else { return };
    if needs_refresh(&dir) {
        write_to(&dir);
    }
}

/// Whether `dir` holds pages another version wrote.
pub fn needs_refresh(dir: &Path) -> bool {
    match std::fs::read_to_string(dir.join("git-scale.1")) {
        Ok(text) => !text.starts_with(&stamp()),
        Err(_) => false,
    }
}

/// Whether `dir` — or, while it does not exist, the nearest directory
/// above it that does — is owned by this user and writable.
fn ours(dir: &Path) -> bool {
    use std::os::unix::fs::MetadataExt;
    let mut at = dir;
    loop {
        if let Ok(meta) = std::fs::metadata(at) {
            // SAFETY: geteuid has no preconditions and cannot fail.
            let uid = unsafe { libc::geteuid() };
            return meta.uid() == uid && writable(at);
        }
        match at.parent() {
            Some(parent) => at = parent,
            None => return false,
        }
    }
}

fn writable(dir: &Path) -> bool {
    let probe = dir.join(format!(".gitscale-probe-{}", std::process::id()));
    match std::fs::write(&probe, b"") {
        Ok(()) => {
            let _ = std::fs::remove_file(&probe);
            true
        }
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("gitscale-man-{}-{}", name, std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn every_page_is_written_and_stamped() {
        let dir = scratch("write");
        let man1 = dir.join("share/man/man1");
        assert_eq!(write_to(&man1), Some(man1.clone()));
        for name in [
            "gitscale",
            "git-scale",
            "git-topic",
            "git-upgrade",
            "git-explain",
        ] {
            let text = std::fs::read_to_string(man1.join(format!("{}.1", name))).unwrap();
            assert!(text.starts_with(&stamp()), "{}", name);
            assert!(text.contains(".TH"), "{}", name);
        }
        assert!(!needs_refresh(&man1));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn pages_from_another_version_are_refreshed_and_missing_ones_not_made() {
        let dir = scratch("refresh");
        assert!(!needs_refresh(&dir));
        std::fs::write(
            dir.join("git-scale.1"),
            ".\\\" generated by gitscale 0.0.1\n",
        )
        .unwrap();
        assert!(needs_refresh(&dir));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_directory_that_cannot_be_written_is_skipped() {
        use std::os::unix::fs::PermissionsExt;
        let dir = scratch("readonly");
        std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(0o555)).unwrap();
        // Root writes anywhere; the test means nothing then.
        if !writable(&dir) {
            assert_eq!(write_to(&dir.join("man1")), None);
            assert!(!dir.join("man1").exists());
        }
        std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(0o755)).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
    }
}
